/**
 * Autonomous AI Agent Runner (safe mode)
 */

import fs from "fs";

function analyzeRepo() {
  const files = fs.readdirSync(".");
  return files;
}

function generateImprovement(files: string[]) {
  if (!files.includes("README.md")) {
    fs.writeFileSync(
      "README.md",
      "# Interview Assistant Pro\n\nAuto-generated by AI Agent."
    );
    return "README created";
  }
  return "No changes";
}

async function run() {
  console.log("AI Agent running...");
  const files = analyzeRepo();
  const result = generateImprovement(files);
  console.log(result);
}

run();
